---
version: "2"

volumes:

  elasticsearch_data:
    driver: "local"

  percona_data:
    driver: "local"

networks:

  net_cache:
  net_db:
  net_jobs:
  net_http:
  net_search:
  traefik-public:
    external: true

services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.0"
    environment:
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - "63002:9200"
    expose:
      - "9300"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    networks:
      - "net_search"

  percona:
    image: "percona:5.6"
    environment:
      - "MYSQL_ROOT_PASSWORD=my-secret-pw"
      - "MYSQL_DATABASE=atom"
      - "MYSQL_USER=atom"
      - "MYSQL_PASSWORD=atom_12345"
    volumes:
      - "percona_data:/var/lib/mysql:rw"
      - "/karangasemkab/docker/etc/mysql/conf.d/:/etc/mysql/conf.d:ro"
    expose:
      - "3306"
    networks:
      - "net_db"

  memcached:
    image: "memcached"
    command: "-p 11211 -m 128 -u memcache"
    expose:
      - "11211"
    networks:
      - "net_cache"
      - "net_jobs"

  gearmand:
    image: "artefactual/gearmand"
    expose:
      - "4730"
    networks:
      - "net_cache"
      - "net_jobs"

  atom:
    image: "pusatsiknjikn/atom:2.4.x"
    command: "fpm"
    volumes:
      - "/karangasemkab/:/atom/src:rw"
    networks:
      - "net_cache"
      - "net_db"
      - "net_http"
      - "net_jobs"
      - "net_search"
    environment:
      - "ATOM_DEVELOPMENT_MODE=on"
      - "ATOM_ELASTICSEARCH_HOST=elasticsearch"
      - "ATOM_MEMCACHED_HOST=memcached"
      - "ATOM_GEARMAND_HOST=gearmand"
      - "ATOM_MYSQL_DSN=mysql:host=percona;port=3306;dbname=atom;charset=utf8"
      - "ATOM_MYSQL_USERNAME=atom"
      - "ATOM_MYSQL_PASSWORD=atom_12345"
      - "ATOM_DEBUG_IP=172.22.0.1"

  atom_worker:
    image: "pusatsiknjikn/atom:2.4.x"
    command: "worker"
    volumes:
      - "/karangasemkab/:/atom/src:rw"
    networks:
      - "net_cache"
      - "net_db"
      - "net_jobs"
      - "net_search"
    environment:
      - "ATOM_DEVELOPMENT_MODE=on"
      - "ATOM_ELASTICSEARCH_HOST=elasticsearch"
      - "ATOM_MEMCACHED_HOST=memcached"
      - "ATOM_GEARMAND_HOST=gearmand"
      - "ATOM_MYSQL_DSN=mysql:host=percona;port=3306;dbname=atom;charset=utf8"
      - "ATOM_MYSQL_USERNAME=atom"
      - "ATOM_MYSQL_PASSWORD=atom_12345"

  nginx:
    image: "nginx:latest"
    volumes:
      - "/karangasemkab/:/atom/src:ro"
      - "/karangasemkab/docker/etc/nginx/prod.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - "net_http"
	  - "traefik-public"
    depends_on:
      - "atom"
	  
	labels:
      - traefik.frontend.rule=Host:nama_simpul.sikn.go.id
      - traefik.enable=true
	  #port disisi container
      - traefik.port=80
      - traefik.tags=traefik-public
      - traefik.docker.network=traefik-public
      # Traefik service that listens to HTTP
      - traefik.redirectorservice.frontend.entryPoints=http
      - traefik.redirectorservice.frontend.redirect.entryPoint=https
      # Traefik service that listens to HTTPS
      - traefik.webservice.frontend.entryPoints=https 
	  
	  
