version: '3.3'

services:

#Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms640m -Xmx640m
      
#  gunakan referensi pada https://docs.docker.com/compose/compose-file/ konfigurasi di bawah digunakan untuk untuk non swarm mode container
    #ulimits:
     # memlock:
       # soft: -1
        #hard: -1
   # mem_limit: 1g

# untuk batasan resource dapat menggunakan seperti contoh di bawah

    #deploy:
      #resources:
        #limits:
          #cpus: '0.50'
          #memory: 50M
        #reservations:
          #cpus: '0.25'
          #memory: 20M
          
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      mode: global
      
    ports:
      - 63002:9200
    expose:
      - 9300
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - net_search

#percona_database
  percona:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=atom
      - MYSQL_USER=atom
      - MYSQL_PASSWORD=atom_12345
    volumes:
      - percona_data:/var/lib/mysql:rw
      # cek penulisan volume
      #- ./etc/mysql/conf.d/:/etc/mysql/conf.d:ro
    expose:
      - 3306
    networks:
      - net_db
#memcached
  memcached:
    image: memcached
    command: -p 11211 -m 128 -u memcache
    expose:
      - 11211
    networks:
      - net_cache
      - net_jobs
#gearmand
  gearmand:
    image: artefactual/gearmand
    expose:
      - "4730"
    networks:
      - net_cache
      - net_jobs  

volumes:
  percona_data:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  net_cache:
    driver: overlay
  net_db:
    driver: overlay
  net_jobs:
    driver: overlay
  net_http:
    driver: overlay
  net_search:
    driver: overlay
