version: '3.3'

services:

#Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    environment:
      #- bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms640m -Xmx640m
      
 #untuk batasan resource dapat menggunakan seperti contoh di bawah
        
    deploy:
      #placement:
        #constraints: [node.role == worker]    
      #resources:
      #  limits:
      #    cpus: '0.50'
      #    memory: 1024M
      #  reservations:
      #    cpus: '0.25'
      #    memory: 512M
    #  mode: global
      
   # ports:
   #   - 63002:9200
    volumes:
      - /sikn/nama_simpul/elasticsearch_data:/usr/share/elasticsearch/data

    networks:
      - net_search

#sesuaikan konfigurasi database
#percona_database
  percona:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=nama_simpul
      - MYSQL_USER=nama_simpul
      - MYSQL_PASSWORD=atom_12345
    volumes:
      - /sikn/nama_simpul/percona_data:/var/lib/mysql:rw
      # sesuaikan lokasi volume 
      - /sikn/nama_simpul/docker/etc/mysql/conf.d/:/etc/mysql/conf.d:ro
    deploy:
      #placement:
        #constraints: [node.role == worker]
      replicas: 1
      #resources:
      #  limits:
      #    cpus: '0.50'
      #    memory: 512M
      #  reservations:
      #    cpus: '0.25'
      #    memory: 256M
    networks:
      - net_db
#memcached
  memcached:
    image: memcached
    command: -p 11211 -m 128 -u memcache
    deploy:
    #  placement:
    #    constraints: [node.role == worker]
      replicas: 1
    #  resources:
    #    limits:
    #      cpus: '0.50'
    #      memory: 128M
    #    reservations:
    #      cpus: '0.25'
    #      memory: 128M
    networks:
      - net_cache
      - net_jobs
#gearmand
  gearmand:
    image: artefactual/gearmand
    deploy:
   #   placement:
   #     constraints: [node.role == worker]
      replicas: 1
   #   resources:
   #     limits:
   #       cpus: '0.50'
   #       memory: 64M
   #     reservations:
   #       cpus: '0.25'
   #       memory: 64M
    networks:
      - net_cache
      - net_jobs  
  
#atom (stable/2.4.x)      
  atom:
    image: pusatsiknjikn/atom:2.4.x
    command: fpm
    # sesuaikan lokasi volume 
    volumes:
      - /sikn/nama_simpul/:/atom/src:rw
    deploy:
      #placement:
        #constraints: [node.role == worker]
      replicas: 1
    #  resources:
    #    limits:
    #      cpus: '0.50'
    #      memory: 128M
    #    reservations:
    #      cpus: '0.25'
    #      memory: 128M
    networks:
      - net_cache
      - net_db
      - net_http
      - net_jobs
      - net_search

    environment:
      - ATOM_DEVELOPMENT_MODE=on
      - ATOM_ELASTICSEARCH_HOST=elasticsearch
      - ATOM_MEMCACHED_HOST=memcached
      - ATOM_GEARMAND_HOST=gearmand
      - ATOM_MYSQL_DSN=mysql:host=percona;port=3306;dbname=nama_simpul;charset=utf8
      - ATOM_MYSQL_USERNAME=nama_simpul
      - ATOM_MYSQL_PASSWORD=atom_12345
      - ATOM_DEBUG_IP=172.22.0.1

#nama_simpul worker      
  worker:
    image: pusatsiknjikn/atom:2.4.x
    command: worker
    volumes:
      - /sikn/nama_simpul/:/atom/src:rw
      - /sikn/nama_simpul/ca-certificates/:/usr/local/share/ca-certificates:ro
    depends_on:
      - gearmand
      - percona

    deploy:
      #placement:
        #constraints: [node.role == worker]
      replicas: 1
    #  resources:
    #    limits:
    #      cpus: '0.50'
    #      memory: 64M
    #    reservations:
    #      cpus: '0.25'
    #      memory: 64M  
      
    networks:
      - net_cache
      - net_db
      - net_jobs
      - net_search
   
    environment:
      - ATOM_DEVELOPMENT_MODE=on
      - ATOM_ELASTICSEARCH_HOST=elasticsearch
      - ATOM_MEMCACHED_HOST=memcached
      - ATOM_GEARMAND_HOST=gearmand
      - ATOM_MYSQL_DSN=mysql:host=percona;port=3306;dbname=nama_simpul;charset=utf8
      - ATOM_MYSQL_USERNAME=nama_simpul
      - ATOM_MYSQL_PASSWORD=atom_12345

 #nginx
  nginx:
    image: nginx:latest
  #  ports:
  #    - 63001:80
      
    # sesuaikan lokasi volume 
    volumes:
      - /sikn/nama_simpul/:/atom/src:ro
      - /sikn/nama_simpul/docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - net_http
      - traefik-public
    deploy:
      #placement:
        #constraints: [node.role == worker]
      replicas: 1
      #resources:
        #limits:
          #cpus: '0.50'
          #memory: 64M
        #reservations:
          #cpus: '0.25'
          #memory: 64M
     # sesuaikan nama domain 
      labels:
        - traefik.frontend.rule=Host:nama_simpul.sikn.go.id
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        
    depends_on:
      - nama_simpul
      
networks:
  net_cache:
    driver: overlay
  net_db:
    driver: overlay
  net_jobs:
    driver: overlay
  net_http:
    driver: overlay
  net_search:
    driver: overlay
  traefik-public:
    external: true
